{% set name = "opentelemetry-instrumentation-boto" %}
{% set version = "0.44b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_boto-{{ version }}.tar.gz
  sha256: 03d47d7b1897b2cf4fd8a085c71588625be9a2a6d0eca0cb5aaa013bdd4cb2bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.44b0
    - opentelemetry-semantic-conventions ==0.44b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-boto 
    # - moto ~=2.0
    # - markupsafe ==2.0.1
    # - boto ~=2.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-boto 
    # - moto ~=2.0
    # - markupsafe ==2.0.1
    # - boto ~=2.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-boto 
    # - moto ~=2.0
    # - markupsafe ==2.0.1
    # - boto ~=2.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-boto 
    # - moto ~=2.0
    # - markupsafe ==2.0.1
    # - boto ~=2.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-boto 
    # - moto ~=2.0
    # - markupsafe ==2.0.1
    # - boto ~=2.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-boto 
    # - moto ~=2.0
    # - markupsafe ==2.0.1
    # - boto ~=2.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-boto 
    # - moto ~=2.0
    # - markupsafe ==2.0.1
    # - boto ~=2.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-boto 
    # - moto ~=2.0
    # - markupsafe ==2.0.1
    # - boto ~=2.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-boto
  summary: OpenTelemetry Boto instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
